### ISSUE TITLE
Segfault in a2_SendEvent() when starting Kobo Redux

### ISSUE THREAD

**Issue by olofson** [olofson/audiality2#253]
DEBUG builds of Audiality 2 segfault in a2_SendEvent() when starting Kobo Redux.
```
==12103== Invalid read of size 8
==12103==    at 0x5377187: a2_SendEvent (internals.h:864)
==12103==    by 0x5377EF3: a2r_em_forwardevent (api.c:409)
==12103==    by 0x537805A: a2r_PumpEngineMessages (api.c:459)
==12103==    by 0x53722B7: a2_AudioCallback (core.c:1856)
==12103==    by 0x538F90E: sdld_callback (sdldrv.c:41)
```
```
#0  0x00007ffff7686255 in a2_SendEvent (q=0x8, e=0xeb0b18) at /home/david/src/audiality2/src/internals.h:864
#1  0x00007ffff7686fc2 in a2r_em_forwardevent (st=0xdf6820, am=0x7fffe9703d20, latelimit=917504) at /home/david/src/audiality2/src/api.c:409
#2  0x00007ffff7687129 in a2r_PumpEngineMessages (st=0xdf6820, latelimit=917504) at /home/david/src/audiality2/src/api.c:459
#3  0x00007ffff7681386 in a2_AudioCallback (driver=0xdf7180, frames=512) at /home/david/src/audiality2/src/core.c:1856
#4  0x00007ffff769e9dd in sdld_callback (ud=0xdf7180, stream=0xdf8ae0 "", len=2048) at /home/david/src/audiality2/src/drivers/sdldrv.c:41
```

Same thing happens with any version back to at least 9ddfa4b444776f0f0f9eb462ab7f9c549f27ba1e.

It doesn't seem like it actually matters if any sounds load or anything, as the same segfault happens anyway.

Disabling all DEBUG macros in config.h has no effect; still segfaults.

**Comment by olofson** [comment]
We are trying to send an A2MT_KILL event to a voice handle with a NULL data pointer. Someone's either creating bogus handles, or destroying handles in an incorrect fashion.
